### ISSUE TITLE
How to use in plain html ?

### ISSUE THREAD

**Issue by ejabu** [shrpne/v-autosize#2]
I already imported static file in my html

`    <script src="../lib/directive.js"></script>
`

this directive.js is based on what I get inside node_modules folder.

but somehow, the result was unexpected.

![image](https://user-images.githubusercontent.com/2019630/59301108-090b0180-8cbb-11e9-8aa2-4732e6ee34f1.png)

**Comment by shrpne** [comment]
please ensure that: 
- "../lib/directive.js" exists
-  Vue script is included
- `autosize` directive is registered

Also you can use this example: https://github.com/shrpne/v-autosize/blob/master/example/index.html

**Comment by ejabu** [comment]
Great answer. Thanks a lot.

I bundled my Vue components using rollup into single javascript file.


It turned out that I had to register directive locally in every single vue file that uses v-autosize.

as it written in readme :



## Register

Register directive locally in the component
```js
import autosize from 'v-autosize';

// Your component
export default {
    directives: {
        autosize,
    }
}
```


I was confused  before, that it worked perfectly by registering globally when using 

```
npm run dev
```
